import styles from '@/styles/Home.module.css';
import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

var works = [
  {
    "title": "Gesture Detection",
    "url": "https://krittin.dev/esign/",
    "description": "Try to detect gesture with Google MediaPipe."
  },
  {
    "title": "Random in Class",
    "url": "https://krittin.dev/randominclass/",
    "description": "Random Complex Sequence with JS libs."
  },
  {
    "title": "24 Game",
    "url": "https://krittin.dev/24game/",
    "description": "Random 24 Game Math Problem with Solution."
  },
  {
    "title": "Vase",
    "url": "https://krittin.dev/vase",
    "description": "Calculate volume of vase with calculus."
  },
  {
    "title": "Popup",
    "url": "https://krittin.dev/popup",
    "description": "Calculate coordinate poist after folded."
  },
  {
    "title": "Faaim",
    "url": "https://krittin.dev/faaim",
    "description": "Count Date with JS libs."
  },
  {
    "title": "Prank Screen",
    "url": "https://krittin.dev/afk/",
    "description": "Simulation of shutting donw screen. (Working well on Google Chrome)"
  },
  {
    "title": "HTML Colors",
    "url": "https://krittin.dev/web-color",
    "description": "Copy color HTML name to clipboard."
  },
  {
    "title": "Keyboard encoder",
    "url": "https://krittin.dev/secret-code",
    "description": "Encrypt text with language switcher."
  },
];

var socials = [
  {
    "url": "https://www.instagram.com/k_suea/",
    "src": "/instagram.svg",
    "alt": "Instagram Logo",
    "size": 24
  },
  {
    "url": "https://www.facebook.com/suea.krittin/",
    "src": "/facebook.svg",
    "alt": "Facebook Logo",
    "size": 16
  },
  {
    "url": "https://www.linkedin.com/in/tuliptgr/",
    "src": "/linkedin.svg",
    "alt": "Linked in Logo",
    "size": 24
  },
  {
    "url": "https://www.github.com/tuliptgr",
    "src": "/github.svg",
    "alt": "Github in Logo",
    "size": 24
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Krittin Kunaree</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Wellcome To&nbsp;
            <code className={styles.code}>krittin.dev</code>
          </p>
          <div className="h-24 flex flex-row flex-wrap gap-4 content-evenly">
            {socials.map(function(social, i){
              return <>
                <a
                  href={social["url"]}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={social["src"]}
                    alt={social["alt"]}
                    className={styles.socialLogo}
                    width={social["size"]}
                    height={social["size"]}
                    priority
                  />
                </a>
              </>;
            })}
          </div>
        </div>

        <div className={styles.center}>
          <div className="flex  flex-col md:flex-row-reverse justify-center items-center">
            <Image 
              src="/profile.png"
              alt="Profile"
              className="rounded-full"
              width={500}
              height={500}
              priority
              />
            <div className="my-16 flex flex-col gap-2 text-center md:text-left">
              <h1 className="text-5xl font-bold ml-4">Krittin Kunaree</h1>
              <h6 className="text-xl ml-4"><code className={styles.code}>Mobile App Developer</code></h6>
            </div>
          </div>
          {/* <div className={styles.thirteen}>
          <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
        </div> */}
        </div>

        <div className={styles.grid}>
          {works.map(function(work, i){
            return <>
              <a
                href={work["url"]}
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
              >
                <h2 className={inter.className}>
                {work["title"]}<span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                {work["description"]}
                </p>
              </a>
            </>;
          })}
        </div>
      </main>
    </>
  );
}